fixed indentation again

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -190,29 +190,26 @@ jobs:
         run: |
           while true; do
             # Fetch the current status of the instance refresh
-          STATUS=$(aws autoscaling describe-instance-refreshes \
-          --auto-scaling-group-name app_asg \
-          --instance-refresh-ids "${REFRESH_ID}" \
-          --query 'InstanceRefreshes[0].Status' \
-          --output text)
+            STATUS=$(aws autoscaling describe-instance-refreshes \
+              --auto-scaling-group-name app_asg \
+              --instance-refresh-ids "${REFRESH_ID}" \
+              --query 'InstanceRefreshes[0].Status' \
+              --output text)
 
-         echo "Instance Refresh Status: $STATUS"
+            echo "Instance Refresh Status: $STATUS"
 
-         # Handle different statuses
-         if [[ "$STATUS" = "Successful" ]]; then
-          echo "Instance refresh completed successfully."
-          break
-         elif [[ "$STATUS" = "Failed" ]]; then
-          echo "Instance refresh failed."
-          exit 1
-         elif [[ "$STATUS" = "Cancelled" ]]; then
-          echo "Instance refresh was cancelled."
-          exit 1
-         else
-          echo "Instance refresh is in progress. Checking again in 30 seconds..."
-          sleep 30
-         fi
-         done
-
-
-
+            # Handle different statuses
+            if [[ "$STATUS" = "Successful" ]]; then
+              echo "Instance refresh completed successfully."
+              break
+            elif [[ "$STATUS" = "Failed" ]]; then
+              echo "Instance refresh failed."
+              exit 1
+            elif [[ "$STATUS" = "Cancelled" ]]; then
+              echo "Instance refresh was cancelled."
+              exit 1
+            else
+              echo "Instance refresh is in progress. Checking again in 30 seconds..."
+              sleep 30
+            fi
+          done
